language: node_js
node_js:
  - "10"
  - "8"

env:
  - CXX=g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6

compiler: g++

sudo: required

os:
  - linux
  - osx

osx_image: xcode7.2
dist: trusty

before_install:
  - export TSD_GITHUB_TOKEN=8591f447276e1caa1b9636b9c8053d768130464f
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - gcc --version
  - openssl version
  - bash ./.travis.sh

script:
  - npm run coverage

after_success:
  - npm run coveralls

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
