language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  
env:
  - CXX=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6

compiler: clang

sudo: required

os:
  - linux
  - os: osx

osx_image: xcode7.2

before_install:
  - export TSD_GITHUB_TOKEN=8591f447276e1caa1b9636b9c8053d768130464f
  - node --version
  - npm --version
  - gcc --version
  - export SOFTHSM_CONF=$PWD/softhsm.conf
  - echo 0:${PWD}/softhsm.db > ${SOFTHSM_CONF}
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install softhsm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install softhsm; fi
  - softhsm --init-token --slot 0 --label token_label --pin 6789 --so-pin 12345 

script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
