language: node_js
node_js:
  - "6"
  
env:
  - CXX=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6

compiler: clang

sudo: required

os:
  - linux

before_install:
  - export TSD_GITHUB_TOKEN=8591f447276e1caa1b9636b9c8053d768130464f
  - node --version
  - npm --version
  - gcc --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh .travis.linux.sh; fi
  - npm install typescript -g
  - npm install tsd -g
  - npm install mocha -g

script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
